import type { Metadata } from "next";
import { Nunito, Roboto } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/contexts/authContext";

const primaryFont = Nunito ({
  subsets: ["latin"], 
  weight: ["400", "700"],
  variable: "--font-primary", 

});
const secondaryFont = Roboto ({
  subsets: ["latin"], 
  weight: ["400", "700"],
  variable: "--font-secondary", 

});

export const metadata: Metadata = {
  title: "Techify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AuthProvider>
    <html
    lang="en" 
    className={`${primaryFont.variable} ${secondaryFont.variable}`}
    >
      <body className={primaryFont.className}>
         < Navbar />
          <main className="container">{children}</main>
         < Footer />
      </body>
    </html>
    </AuthProvider>
  );
}
